version: '3.8'
services:
  app:
    build: .
    volumes:
      - ./:/app  # This critical line syncs host↔container
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    # Add other configs as needed
